<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <!--<PublishSingleFile>true</PublishSingleFile>-->
        <SelfContained>true</SelfContained>
        <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <SatelliteResourceLanguages>none</SatelliteResourceLanguages>
        <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".VS2022", ""))</RootNamespace>
        <AssemblyName>AutoCode</AssemblyName>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <Company>https://github.com/yuanrui</Company>
        <Copyright>Copyright © YuanRui 2017-2025</Copyright>
        <Product>Banana.AutoCode</Product>
        <Title>AutoCode</Title>
        <Authors>YuanRui</Authors>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Core\Microsoft.VisualStudio.TextTemplating\**" />
      <Compile Remove="Core\Mono.TextTemplating\**" />
      <EmbeddedResource Remove="Core\Microsoft.VisualStudio.TextTemplating\**" />
      <EmbeddedResource Remove="Core\Mono.TextTemplating\**" />
      <None Remove="Core\Microsoft.VisualStudio.TextTemplating\**" />
      <None Remove="Core\Mono.TextTemplating\**" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Properties\AssemblyInfo.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="app.config" />
        <None Remove="Banana.AutoCode.suo" />
        <None Remove="packages.config" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DM.DmProvider" Version="8.3.1.36935" />
        <PackageReference Include="DockPanelSuite" Version="3.1.1" />
        <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
        <PackageReference Include="MySqlConnector" Version="2.4.0" />
        <PackageReference Include="Npgsql" Version="9.0.3" />
        <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.8.0" />
        <PackageReference Include="System.CodeDom" Version="9.0.5" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.5" />
        <PackageReference Include="System.Data.Odbc" Version="9.0.5" />
        <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Config\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\EasyUI\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\EntityFramework\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Java\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Layui\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\MySQL\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Oracle\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Samples\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\SqlSugar\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Test\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Thrift\*.tt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Templates\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <None Update="AutoCode.dll.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\JavaScript\TypeScriptEntity.tt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\Java\JPA\Entity.tt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\Java\JPA\Repository.tt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\Java\MyBatis\Entity.tt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\Java\MyBatis\MySqlDao.tt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\Thrift\Common.thrift">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>