//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banana.AutoCode.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Banana.AutoCode.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Finish generate table {0} code. 的本地化字符串。
        /// </summary>
        internal static string Finish_Generate {
            get {
                return ResourceManager.GetString("Finish_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish generate table {0} code, no result. 的本地化字符串。
        /// </summary>
        internal static string Finish_Generate_Empty {
            get {
                return ResourceManager.GetString("Finish_Generate_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate table:{0} TemplateName:{1} OutputPath:{2} 的本地化字符串。
        /// </summary>
        internal static string Generate_Table {
            get {
                return ResourceManager.GetString("Generate_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin generate Thrift 的本地化字符串。
        /// </summary>
        internal static string Generate_Thrift_Begin {
            get {
                return ResourceManager.GetString("Generate_Thrift_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Thrift({0}) Exception:{1} 的本地化字符串。
        /// </summary>
        internal static string Generate_Thrift_Exception {
            get {
                return ResourceManager.GetString("Generate_Thrift_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished generate Thrift 的本地化字符串。
        /// </summary>
        internal static string Generate_Thrift_Finished {
            get {
                return ResourceManager.GetString("Generate_Thrift_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No template file. run stop. 的本地化字符串。
        /// </summary>
        internal static string No_Template_File {
            get {
                return ResourceManager.GetString("No_Template_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output directory not exists, auto create. 的本地化字符串。
        /// </summary>
        internal static string Output_Not_Exists {
            get {
                return ResourceManager.GetString("Output_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error remove db connection settings, Exception:  的本地化字符串。
        /// </summary>
        internal static string Remove_ConnectionString_Exception {
            get {
                return ResourceManager.GetString("Remove_ConnectionString_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove db connection settings {0} success 的本地化字符串。
        /// </summary>
        internal static string Remove_ConnectionString_Success {
            get {
                return ResourceManager.GetString("Remove_ConnectionString_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error writing db connection settings, Exception:  的本地化字符串。
        /// </summary>
        internal static string Save_ConnectionString_Exception {
            get {
                return ResourceManager.GetString("Save_ConnectionString_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save db connection settings {0} success 的本地化字符串。
        /// </summary>
        internal static string Save_ConnectionString_Success {
            get {
                return ResourceManager.GetString("Save_ConnectionString_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error writing app settings 的本地化字符串。
        /// </summary>
        internal static string Save_Setting_Exception {
            get {
                return ResourceManager.GetString("Save_Setting_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save settings {0}={1} success 的本地化字符串。
        /// </summary>
        internal static string Save_Setting_Success {
            get {
                return ResourceManager.GetString("Save_Setting_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File(*.txt)|*.txt|All File(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string SaveFileDialog_Filter {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template: 的本地化字符串。
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates directory not exists, auto create. 的本地化字符串。
        /// </summary>
        internal static string Templates_Not_Exists {
            get {
                return ResourceManager.GetString("Templates_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template directory:{0} not exists. 的本地化字符串。
        /// </summary>
        internal static string Templates_Not_Exists_Format {
            get {
                return ResourceManager.GetString("Templates_Not_Exists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template directory:{0} not exists, auto created. 的本地化字符串。
        /// </summary>
        internal static string Templates_Not_Exists_Format_Auto {
            get {
                return ResourceManager.GetString("Templates_Not_Exists_Format_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unchecked tables can not generate code. 的本地化字符串。
        /// </summary>
        internal static string Unchecked_Tables {
            get {
                return ResourceManager.GetString("Unchecked_Tables", resourceCulture);
            }
        }
    }
}
